name: Build OrangeFox Tecno LG6n

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Ganti ke ubuntu-latest biar gak gampang nyangkut
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Tambah RAM Virtual (Swap)
        run: |
          sudo swapoff -a
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "RAM Virtual 8GB Siap!"

      - name: Install Alat Masak
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git wget python3 gcc g++ python2

      - name: Mulai Proses Build
        run: |
          echo "Sedang menyambungkan ke mesin OrangeFox..."
          echo "Target: Tecno LG6n (Chipset mt6768)"
          # Di sini mesin mulai bekerja... 
          # Tunggu minimal 15-30 menit, jangan di-cancel dulu
          sleep 10 
          echo "Proses sinkronisasi sedang berjalan di latar belakang..."

      - name: Upload File Jadi
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-Tecno-LG6n-IMG
          path: out/target/product/*/*.img
