name: Build OrangeFox Tecno LG6n

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Sync OrangeFox Source
        run: |
          mkdir fox && cd fox
          repo init --depth=1 -u https://github.com -b fox_12.1
          repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Bongkar Device Tree
        run: |
          mkdir -p fox/device/tecno/LG6n
          unzip Device_Tree_Orange*.zip -d fox/device/tecno/LG6n

      - name: Build Recovery
        run: |
          cd fox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_VERSION="R11.1_Unofficial"
          export LC_ALL="C"
          lunch omni_TECNO-LG6n-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Hasil
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-LG6n
          path: fox/out/target/product/LG6n/*.img
