name: Build OrangeFox Tecno LG6n

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil Bahan Tree
        uses: actions/checkout@v4

      - name: 2. Siapin Alat Tempur
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git wget python3 gcc g++ libssl-dev repo

      - name: 3. Download Source OrangeFox
        run: |
          mkdir fox && cd fox
          repo init --depth=1 -u https://github.com -b fox_12.1
          repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: 4. Pindahin Tree ke Folder Source
        run: |
          mkdir -p fox/device/tecno/LG6n
          cp -r device/tecno/TECNO-LG6n/* fox/device/tecno/LG6n/

      - name: 5. Mulai Masak (Compile)
        run: |
          cd fox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_VERSION="R11.1_Unofficial"
          export LC_ALL="C"
          lunch omni_TECNO-LG6n-eng
          mka recoveryimage -j$(nproc --all)

      - name: 6. Upload Hasil Jadi
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-LG6n
          path: fox/out/target/product/LG6n/*.img
