name: Ekstrak Cepat

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tata-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Ambil File
        uses: actions/checkout@v4

      - name: Bongkar ZIP Otomatis
        run: |
          # Buat folder tujuan
          mkdir -p device/tecno/TECNO-LG6n
          
          # Ekstrak file ZIP (pastikan ada file .zip di repo)
          unzip -o *.zip -d device/tecno/TECNO-LG6n/ || echo "File ZIP tidak ditemukan"
          
          # Hapus ZIP asli agar tidak double
          rm -f *.zip

      - name: Simpan Perubahan ke Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Folder device/tecno/TECNO-LG6n sudah rapi!"
