name: Build OrangeFox Real

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Bahan
        uses: actions/checkout@v4

      - name: Ambil Alat (AIK)
        run: |
          # Menggunakan Git Clone agar file tidak korup/rusak
          git clone https://github.com AIK
          chmod -R 755 AIK/

      - name: Proses Menjadi IMG
        run: |
          mkdir -p output
          
          # Mencari file .img di dalam folder device/tecno/TECNO-LG6n/
          FILE_IMG=$(find device/tecno/TECNO-LG6n/ -name "*.img" | head -n 1)
          
          if [ -z "$FILE_IMG" ]; then
            echo "--- ERROR: FILE .IMG TIDAK KETEMU DI FOLDER DEVICE! ---"
            exit 1
          fi

          echo "Sedang memproses: $FILE_IMG"
          cp "$FILE_IMG" AIK/boot.img
          
          cd AIK/
          # Perintah bongkar dan bungkus ulang (Repack)
          ./unpackimg.sh boot.img
          ./repackimg.sh
          
          # Pindahkan hasil jadinya ke folder luar
          if; then
            mv image-new.img ../output/OrangeFox-Tecno-LG6n.img
            echo "BERHASIL: File .img sudah jadi!"
          else
            echo "GAGAL: File hasil repack tidak muncul!"
            exit 1
          fi

      - name: Download Hasil Jadi
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-Project-Hasil
          path: output/
